MVC/Controllers/DailyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Abstract;
using DAL;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers
{
    public class DailyController : Controller
    {
        private readonly DailyPlanService dailyPlanService;

        public DailyController(DailyPlanService dailyPlanService)
        {
            this.dailyPlanService = dailyPlanService;
        }
        public IActionResult Index()
        {
            return View(dailyPlanService.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DailyPlan model)
        {
            if (ModelState.IsValid)
            {
                dailyPlanService.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(Guid id)
        {
            DailyPlan dailyPlan = dailyPlanService.GetById(id);
           
            return View(dailyPlan);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DailyPlan daily)
        {
            if (ModelState.IsValid)
            {
                dailyPlanService.Update(daily);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }

        }
        public ActionResult Delete(Guid id)
        {
            return View(dailyPlanService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(DailyPlan daily)
        {
            try
            {
                dailyPlanService.Remove(daily.ID);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/Controllers/MountlyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Abstract;
using DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MVC.Controllers
{
    public class MountlyController : Controller
    {
        private readonly MountlyPlanService mountlyPlanService;

        public MountlyController(MountlyPlanService mountlyPlanService)
        {
            this.mountlyPlanService = mountlyPlanService;
        }
        public IActionResult Index()
        {
            return View(mountlyPlanService.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(MontlyPlan model)
        {
            if (ModelState.IsValid)
            {
                mountlyPlanService.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(Guid id)
        {
          MontlyPlan  mountlyPlan  = mountlyPlanService.GetById(id);

            return View(mountlyPlan);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MontlyPlan model)
        {
            if (ModelState.IsValid)
            {
                mountlyPlanService.Update(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }

        }
        public ActionResult Delete(Guid id)
        {
            return View(mountlyPlanService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MontlyPlan model)
        {
            try
            {
                mountlyPlanService.Remove(model.ID);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/Controllers/WeeklyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Abstract;
using BLL.Repository;
using DAL;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers
{
    public class WeeklyController : Controller
    {
        private readonly WeeklyPlanService weeklyPlanService;

        public WeeklyController(WeeklyPlanService weeklyPlanService)
        {
            this.weeklyPlanService = weeklyPlanService;
        }
        public IActionResult Index()
        {
            return View(weeklyPlanService.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(WeeklyPlan model)
        {
            if (ModelState.IsValid)
            {
               weeklyPlanService.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(Guid id)
        {
            WeeklyPlan weeklyPlan = weeklyPlanService.GetById(id);

            return View(weeklyPlan);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WeeklyPlan model)
        {
            if (ModelState.IsValid)
            {
                weeklyPlanService.Update(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }

        }
        public ActionResult Delete(Guid id)
        {
            return View(weeklyPlanService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(WeeklyPlan model)
        {
            try
            {
                weeklyPlanService.Remove(model.ID);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/Views/Daily/Create.cshtml
@model DailyPlan  
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h2>Günlük Plan Oluştur</h2>
    </div>
    <form role="form" asp-action="Create" asp-controller="Daily" method="post" enctype="multipart/form-data">

        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="form-group">
                            <label>Plan Ekle</label>
                            <input asp-for="dailyPlan" type="text" class="form-control" placeholder="Plan açıklaması girin" />
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Oluştur</button>
        </div>
    </form>
</div>

MVC/Views/Daily/Delete.cshtml
@model DailyPlan
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <form role="form" asp-action="Delete" asp-controller="Daily" method="post">

            <p>@Model.dailyPlan planını silmek istediğinizden emin misiniz?</p>
            <button class="btn btn-danger">Evet</button>
            <a asp-action="Index" asp-controller="Daily" class="btn">Hayır</a>
        </form>
    </div>
</div>

MVC/Views/Daily/Edit.cshtml
@model DailyPlan
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <form role="form" asp-action="Edit" asp-controller="Daily" method="post">
        <div class="card-body">
            <div class="row">
                <div class="card-card-primary">

                    <div class="card-body">
                        <label>Plan</label>
                        <input asp-for="dailyPlan" type="text" class="form-control" placeholder="Günlük plan girin" />
                    </div>

                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Güncelle</button>
        </div>
    </form>
</div>

MVC/Views/Daily/Index.cshtml
@model IEnumerable<DAL.DailyPlan>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <a asp-action="Create" asp-controller="Daily" class="btn btn-primary float-right">Günlük Plan Ekle</a>
    </div>
    <div class="card-body">
        <table id="dailytable" class="table table-striped">
            <thead>
                <tr>
                    
                    <th>Açıklama</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.dailyPlan</td>
                        <td>
                            <a asp-controller="Daily" asp-action="Edit" asp-route-id="@item.ID" class="btn btn-sm btn-warning">Planı Güncelle</a>
                            <a asp-controller="Daily" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-sm btn-danger">Planı Sil</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>
@section scripts{
    <script>
    $(document).ready(function () {
            $('#dailytable').DataTable();
        });</script>


}

MVC/Views/Mountly/Create.cshtml
@model MontlyPlan
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h2>Aylık Plan Oluştur</h2>
    </div>
    <form role="form" asp-action="Create" asp-controller="Mountly" method="post" enctype="multipart/form-data">

        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="form-group">
                            <label>Plan Ekle</label>
                            <input asp-for="mountlyPlan" type="text" class="form-control" placeholder="Plan açıklaması girin" />
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Oluştur</button>
        </div>
    </form>
</div>

MVC/Views/Mountly/Delete.cshtml
@model MontlyPlan
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <form role="form" asp-action="Delete" asp-controller="Mountly" method="post">

            <p>@Model.mountlyPlan planını silmek istediğinizden emin misiniz?</p>
            <button class="btn btn-danger">Evet</button>
            <a asp-action="Index" asp-controller="Mountly" class="btn">Hayır</a>
        </form>
    </div>
</div>
//

MVC/Views/Mountly/Edit.cshtml
@model MontlyPlan
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <form role="form" asp-action="Edit" asp-controller="Mountly" method="post">
        <div class="card-body">
            <div class="row">
                <div class="card-card-primary">

                    <div class="card-body">
                        <label>Plan</label>
                        <input asp-for="mountlyPlan" type="text" class="form-control" placeholder="Aylık plan girin" />
                    </div>

                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Güncelle</button>
        </div>
    </form>
</div>

MVC/Views/Mountly/Index.cshtml
@model IEnumerable<DAL.MontlyPlan>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <a asp-action="Create" asp-controller="Weekly" class="btn btn-primary float-right">Aylık Plan Ekle</a>
    </div>
    <div class="card-body">
        <table id="dailytable" class="table table-striped">
            <thead>
                <tr>

                    <th>Açıklama</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.mountlyPlan</td>
                        <td>
                            <a asp-controller="Mountly" asp-action="Edit" asp-route-id="@item.ID" class="btn btn-sm btn-warning">Planı Güncelle</a>
                            <a asp-controller="Mountly" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-sm btn-danger">Planı Sil</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>
@section scripts{
    <script>
    $(document).ready(function () {
            $('#dailytable').DataTable();
        });</script>


}

MVC/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}




<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Görev Yöneticisi Paneli</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="~/https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->

        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Daily" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Günlük Plan
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Weekly" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Haftalık Plan
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Mountly" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Aylık Plan
                                </p>
                            </a>
                        </li>



                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> @ViewData["Title"]</h1>
                        </div><!-- /.col -->

                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2019 <a href="/Home/Index">Siteye Git</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.0.2
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button)</script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>
    <script src="~/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

MVC/Views/Weekly/Create.cshtml
@model WeeklyPlan
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h2>Haftalık Plan Oluştur</h2>
    </div>
    <form role="form" asp-action="Create" asp-controller="Weekly" method="post" enctype="multipart/form-data">

        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="form-group">
                            <label>Plan Ekle</label>
                            <input asp-for="weeklyPlan" type="text" class="form-control" placeholder="Plan açıklaması girin" />
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Oluştur</button>
        </div>
    </form>
</div>

MVC/Views/Weekly/Delete.cshtml
@model WeeklyPlan
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <form role="form" asp-action="Delete" asp-controller="Weekly" method="post">

            <p>@Model.weeklyPlan planını silmek istediğinizden emin misiniz?</p>
            <button class="btn btn-danger">Evet</button>
            <a asp-action="Index" asp-controller="Daily" class="btn">Hayır</a>
        </form>
    </div>
</div>

MVC/Views/Weekly/Edit.cshtml
@model WeeklyPlan
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <form role="form" asp-action="Edit" asp-controller="Weekly" method="post">
        <div class="card-body">
            <div class="row">
                <div class="card-card-primary">

                    <div class="card-body">
                        <label>Plan</label>
                        <input asp-for="weeklyPlan" type="text" class="form-control" placeholder="Haftalık plan girin" />
                    </div>

                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Güncelle</button>
        </div>
    </form>
</div>

MVC/Views/Weekly/Index.cshtml
@model IEnumerable<DAL.WeeklyPlan>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <a asp-action="Create" asp-controller="Weekly" class="btn btn-primary float-right">Haftalık Plan Ekle</a>
    </div>
    <div class="card-body">
        <table id="dailytable" class="table table-striped">
            <thead>
                <tr>
                    
                    <th>Açıklama</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.weeklyPlan</td>
                        <td>
                            <a asp-controller="Weekly" asp-action="Edit" asp-route-id="@item.ID" class="btn btn-sm btn-warning">Planı Güncelle</a>
                            <a asp-controller="Weekly" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-sm btn-danger">Planı Sil</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>
@section scripts{
    <script>
    $(document).ready(function () {
            $('#dailytable').DataTable();
        });</script>


    }